name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs: 
  CI:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:      
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with: 
          file: ./src/Dockerfile # onde está o docker file
          context: ./src # o que será enviado para o docker daemon
          push: true #definir se haverá o push
          tags: |
            ygortfive/kube-news:latest
            ygortfive/kube-news:${{github.run_number}}